version: "3"
services:
  nginx:
    image: compose_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    depends_on:
      php:
        condition: service_healthy
    environment:
      - ENV=development
  php:
    image: compose_php
    volumes:
      - ./www:/var/www
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s