# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        build: ./images/nginx
        #image: nginx:latest
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"            
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
        depends_on:
            php:
                condition: service_healthy
        environment:
            - ENV=development
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
        healthcheck:
            test: ["CMD", "php-fpm", "-t"]
            interval: 3s
            timeout: 5s
            retries: 5
            start_period: 1s